apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namePrefix: dev-
images:
- name: 821604620465.dkr.ecr.ap-northeast-2.amazonaws.com/jeanne-ecr
  newName: 821604620465.dkr.ecr.ap-northeast-2.amazonaws.com/jeanne-ecr
  newTag: cffaf4fa
resources:
- ../base
patchesStrategicMerge:
- deployment-patch.yaml
- ingress-patch.yaml
- service-patch.yaml
