apiVersion: v1
items:
- apiVersion: v1
  kind: Service
  metadata:
    annotations:
      meta.helm.sh/release-name: argocd
      meta.helm.sh/release-namespace: argo
    creationTimestamp: "2022-04-15T11:23:08Z"
    labels:
      app.kubernetes.io/component: application-controller
      app.kubernetes.io/instance: argocd
      app.kubernetes.io/managed-by: Helm
      app.kubernetes.io/name: argocd-application-controller
      app.kubernetes.io/part-of: argocd
      helm.sh/chart: argo-cd-3.26.9
    name: argocd-application-controller
    namespace: argo
    resourceVersion: "28071"
    uid: b55d8c46-7ac5-413c-9bd7-a9713b145383
  spec:
    clusterIP: 10.108.152.223
    clusterIPs:
    - 10.108.152.223
    internalTrafficPolicy: Cluster
    ipFamilies:
    - IPv4
    ipFamilyPolicy: SingleStack
    ports:
    - name: https-controller
      port: 8082
      protocol: TCP
      targetPort: 8082
    selector:
      app.kubernetes.io/instance: argocd
      app.kubernetes.io/name: argocd-application-controller
    sessionAffinity: None
    type: ClusterIP
  status:
    loadBalancer: {}
- apiVersion: v1
  kind: Service
  metadata:
    annotations:
      meta.helm.sh/release-name: argocd
      meta.helm.sh/release-namespace: argo
    creationTimestamp: "2022-04-15T11:23:08Z"
    labels:
      app.kubernetes.io/component: dex-server
      app.kubernetes.io/instance: argocd
      app.kubernetes.io/managed-by: Helm
      app.kubernetes.io/name: argocd-dex-server
      app.kubernetes.io/part-of: argocd
      helm.sh/chart: argo-cd-3.26.9
    name: argocd-dex-server
    namespace: argo
    resourceVersion: "28073"
    uid: fed32a2a-1773-498c-b666-7cc8df3a82e8
  spec:
    clusterIP: 10.104.3.135
    clusterIPs:
    - 10.104.3.135
    internalTrafficPolicy: Cluster
    ipFamilies:
    - IPv4
    ipFamilyPolicy: SingleStack
    ports:
    - name: http
      port: 5556
      protocol: TCP
      targetPort: http
    - name: grpc
      port: 5557
      protocol: TCP
      targetPort: grpc
    selector:
      app.kubernetes.io/instance: argocd
      app.kubernetes.io/name: argocd-dex-server
    sessionAffinity: None
    type: ClusterIP
  status:
    loadBalancer: {}
- apiVersion: v1
  kind: Service
  metadata:
    annotations:
      meta.helm.sh/release-name: argocd
      meta.helm.sh/release-namespace: argo
    creationTimestamp: "2022-04-15T11:23:08Z"
    labels:
      app.kubernetes.io/component: redis
      app.kubernetes.io/instance: argocd
      app.kubernetes.io/managed-by: Helm
      app.kubernetes.io/name: argocd-redis
      app.kubernetes.io/part-of: argocd
      helm.sh/chart: argo-cd-3.26.9
    name: argocd-redis
    namespace: argo
    resourceVersion: "28079"
    uid: 377de728-9557-4c59-8e3f-f6b89b30deb0
  spec:
    clusterIP: 10.99.39.163
    clusterIPs:
    - 10.99.39.163
    internalTrafficPolicy: Cluster
    ipFamilies:
    - IPv4
    ipFamilyPolicy: SingleStack
    ports:
    - name: redis
      port: 6379
      protocol: TCP
      targetPort: 6379
    selector:
      app.kubernetes.io/instance: argocd
      app.kubernetes.io/name: argocd-redis
    sessionAffinity: None
    type: ClusterIP
  status:
    loadBalancer: {}
- apiVersion: v1
  kind: Service
  metadata:
    annotations:
      meta.helm.sh/release-name: argocd
      meta.helm.sh/release-namespace: argo
    creationTimestamp: "2022-04-15T11:23:08Z"
    labels:
      app.kubernetes.io/component: repo-server
      app.kubernetes.io/instance: argocd
      app.kubernetes.io/managed-by: Helm
      app.kubernetes.io/name: argocd-repo-server
      app.kubernetes.io/part-of: argocd
      helm.sh/chart: argo-cd-3.26.9
    name: argocd-repo-server
    namespace: argo
    resourceVersion: "28081"
    uid: d2cdd4f5-0693-4b20-a9dd-8e83cdc8b117
  spec:
    clusterIP: 10.100.243.25
    clusterIPs:
    - 10.100.243.25
    internalTrafficPolicy: Cluster
    ipFamilies:
    - IPv4
    ipFamilyPolicy: SingleStack
    ports:
    - name: https-repo-server
      port: 8081
      protocol: TCP
      targetPort: repo-server
    selector:
      app.kubernetes.io/instance: argocd
      app.kubernetes.io/name: argocd-repo-server
    sessionAffinity: None
    type: ClusterIP
  status:
    loadBalancer: {}
- apiVersion: v1
  kind: Service
  metadata:
    annotations:
      meta.helm.sh/release-name: argocd
      meta.helm.sh/release-namespace: argo
    creationTimestamp: "2022-04-15T11:23:08Z"
    labels:
      app.kubernetes.io/component: server
      app.kubernetes.io/instance: argocd
      app.kubernetes.io/managed-by: Helm
      app.kubernetes.io/name: argocd-server
      app.kubernetes.io/part-of: argocd
      helm.sh/chart: argo-cd-3.26.9
    name: argocd-server
    namespace: argo
    resourceVersion: "28089"
    uid: 2a6e77e2-65fa-4841-b5d4-1e5391a32111
  spec:
    clusterIP: 10.103.77.216
    clusterIPs:
    - 10.103.77.216
    externalTrafficPolicy: Cluster
    internalTrafficPolicy: Cluster
    ipFamilies:
    - IPv4
    ipFamilyPolicy: SingleStack
    ports:
    - name: http
      nodePort: 30080
      port: 80
      protocol: TCP
      targetPort: 8080
    - name: https
      nodePort: 30443
      port: 443
      protocol: TCP
      targetPort: 8080
    selector:
      app.kubernetes.io/instance: argocd
      app.kubernetes.io/name: argocd-server
    sessionAffinity: None
    type: NodePort
  status:
    loadBalancer: {}
kind: List
metadata:
  resourceVersion: ""
  selfLink: ""
